### ISSUE TITLE
Consuming messages not working with Kafka version 0.11

### ISSUE THREAD

**Issue by singh1469** [Blizzard/node-rdkafka#239]
node-rdkafka (version 1.0.6) and Kafka (version 0.11) works fine when producing messages, however consuming messages does NOT work.
- The consumer fires the `ready` event
- The consumer does NOT receive any error messages (`debug = 'all'` is set)
- No messages are received by the consumer when generating messages via Kafka container e.g.
`kafka-console-consumer --zookeeper myzookeeper:2181 --topic my_topic`

I'm using the confluent containers available here:
https://hub.docker.com/r/confluentinc/cp-kafka/

Specifically I'm using tag: 3.3
`confluentinc/cp-kafka:3.3.0`

Documentation mentions this (Docker) tag uses Kafka version 0.11
Confirmed here - http://docs.confluent.io/current/release-notes.html

**NB Please note everything works as expected when using the following tag:**
`confluentinc/cp-kafka:3.2.0`
This uses Kafka version 0.10.2.1
http://docs.confluent.io/3.2.2/release-notes.html#apache-kafka-0-10-2-1

**Comment by kmonchamp** [comment]
I am seeing the exact same behavior when consuming with the confluent docker images in the 3.3.0 tag.   

Has anyone tested with standard kafka 0.11 builds?

**Comment by ancashoria** [comment]
I'm using this `docker-compose.yml` from Confluent 3.3.0
https://github.com/confluentinc/cp-docker-images/blob/3.3.x/examples/cp-all-in-one/docker-compose.yml
I am not receiving messages using node-rdkafka.
Can you guys do a quick test using that docker-compose?

**Comment by webmakersteve** [comment]
What is your full client configuration? I wonder if you need to specify to request the api version to get this to work appropriately. If you give me a sample of of the code you're using I can try to reproduce this and figure it out.

**Comment by webmakersteve** [comment]
I just released a new version of node-rdkafka with 0.11.1. It may be worth trying one more time.

**Comment by ancashoria** [comment]
Didn't fix the issue for me. 
Could be something on my side, but I spent so much time on this that I really don't know what to try next.
Thanks for your hard work @webmakersteve

**Comment by FuzzOli87** [comment]
@webmakersteve I'm seeing the same issue with the following code:
`
import kafka from 'node-rdkafka';

const producer = new kafka.Producer({
  'metadata.broker.list': 'parkhub-kafka-confluent:9092',
  'api.version.request': true,
  dr_cb: true
});

console.log('CONNECTING!');
producer.connect();
console.log('CONNECTING! DONE');

producer.on('ready', () => {
  console.log('CONNECTED');

  const consumer = new kafka.KafkaConsumer({
    'metadata.broker.list': 'parkhub-kafka-confluent:9092',
    'api.version.request': true,
    // debug: 'all',
    'group.id': 'TEST'
  });

  console.log('CONNECTING! to consumer');
  consumer.connect();
  console.log('CONNECTING! DONE consumer');

  consumer.on('ready', () => {
    console.log('CONNECTED consumer');
    consumer.subscribe(['topico']);
    consumer.consume();
  });

  consumer.on('data', (data) => {
    console.log('C-GOT DATA!');
    console.log(data)
  });
  consumer.on('event', (err) => {
    console.log('C-event');
    console.log(err);
  });
  consumer.on('event.log', (err) => {
    console.log('C-event.log');
    console.log(err);
  });

  consumer.on('event.error', (err) => {
    console.error('C-ERROR FROM event ');
    console.error(err);
  });
  try {
    setInterval(() => {
      console.log('producing!');
      producer.produce('topico', null, new Buffer('MESSAGE!'))
    }, 5000);

  } catch(e) {
    console.error('ERROR FROM PRODUCER')
    console.error(err);
  }
});

producer.on('event', (err) => {
  console.log('event');
  console.log(err);
});
producer.on('event.log', (err) => {
  console.log('event.log');
  console.log(err);
});

producer.on('event.error', (err) => {
  console.error('ERROR FROM event ');
  console.error(err);
});

`

Using Dockerfile:
`
# ---- Base Node Kafka/GRPC Image ----
FROM node:8-alpine AS base
LABEL maintainer Daniel Olivares "daniel.olivares@parkhub.com"

RUN apk --update --upgrade add --virtual build-deps \
cyrus-sasl-dev \
make \
g++ \
bash \
python 

RUN apk add --update --upgrade --no-cache tini \
  librdkafka-dev --repository http://dl-3.alpinelinux.org/alpine/edge/community --allow-untrusted

ARG BUILD_LIBRDKAFKA=0
ENV BUILD_LIBRDKAFKA=0
RUN mkdir /home/app

WORKDIR /home/app

COPY package.json .

RUN npm install

ENTRYPOINT ["/sbin/tini", "--"]

CMD ["node", "index.js"]

`

**Comment by FuzzOli87** [comment]
UPDATE:

My consumers are now consuming. I was able to run it with the following docker-compose:
```
version: '3'
networks: 
 microservices-network: {}
services:
  kafka-confluent:
    image: confluentinc/cp-enterprise-kafka
    container_name: 'kafka-confluent-container'
    hostname: kafka-confluent
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 9999:9999
    env_file:
      - kafka.env
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - microservices-network
  zookeeper:
    image: zk-confluent:latest
    hostname: zookeeper
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    environment:
      ZOOKEEPER_REPLICAS: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_PORT: 2888
      ZOOKEEPER_ELECTION_PORT: 3888
      ZOOKEEPER_SERVER_ID: 1
    networks:
      - microservices-network
    # volumes:
    #   - /tmp/zookeeper/data:/data
  # kafka-manager:
  #   image: solsson/kafka-manager
  #   depends_on:
  #     - zookeeper
  #   ports:
  #     - 9009:9000
  #   environment:
  #     ZK_HOSTS: zookeeper:2181
  #   networks:
  #     - microservices-network
  schema_registry:
    image: confluentinc/cp-schema-registry
    hostname: schema_registry
    depends_on:
      - zookeeper
      - kafka-confluent
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema_registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'
    networks:
      - microservices-network
  control-center:
    image: confluentinc/cp-enterprise-control-center:3.3.0
    hostname: control-center
    ports:
      - 9021:9021
    depends_on:
      - kafka-confluent
      - zookeeper
      - schema_registry
    environment:
      CONTROL_CENTER_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka-confluent:9092'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021
    networks:
      - microservices-network
```

kafka.env file:
```
KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-confluent:9092
KAFKA_BROKER_ID=1
KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
# KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
KAFKA_JMX_PORT=9999
KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
```

My application was using this docker-compose file:
```
version: '3'
services:
  kafka-consumer-test:
    build:
      context: .
    container_name: 'kafka-consumer-test'
    command: npm run start-dev-c
    volumes:
      - ./:/home/app
    external_links:
      - kafka-confluent-container:kafka
  kafka-test:
    build:
      context: .
    container_name: 'kafka-test'
    command: npm run start-dev
    volumes:
      - ./:/home/app
    external_links:
      - kafka-confluent-container:kafka
networks:
  default:
    external:
      name: confluent_microservices-network
```

NOTE: The network name might be different depending on where you run your docker-compose file bc it uses the current directory to build the network name.

I was also able to consume/produce using cp-kafka:3.3.0

I had a whole bunch of other environment configurations so my gut tells me that one of them is the culprit.

**Comment by webmakersteve** [comment]
Good find! I would not be against using the confluent kafka containers for the end to end tests if anyone is feeling interested in a PR :)

**Comment by deyceg** [comment]
@FuzzOli87 Did you find out what as causing the issue? We've upgraded from 0.10 and having the same issue with consuming using confluent containers.

**Comment by webmakersteve** [comment]
https://github.com/Blizzard/node-rdkafka/blob/master/docker-compose.yml

I updated the end to end tests to use confluent and they work, however I'm using the community versions.

Do the tests pass for you when using the packaged docker-compose?
