### ISSUE TITLE
KafkaConsumer hangs in disconnect indefinitely when option `rebalance_cb: true`

### ISSUE THREAD

**Issue by sprijk** [Blizzard/node-rdkafka#330]
This works:

- Start a KafkaConsumer
- Consume a few messages
- Call `disconnect(cb)` with callback function 
- Callback function is called

This does not work:

- Start a KafkaConsumer with option `rebalance_cb: true`
- Consume a few messages
- Call `disconnect(cb)` with callback function 
- Callback function is *never* called

**Comment by sprijk** [comment]
See this outcome:
```
$ mocha --require coffee-script/register test.coffee 
  Consumer diconnect
    WITHOUT rebalance_cb
      ✓ should consume data (217ms)
      ✓ should disconnect (110ms)
    WITH rebalance_cb
rebalance
      ✓ should consume data (1034ms)
rebalance
      1) should disconnect

  3 passing (14s)
  1 failing

  1) Consumer diconnect
       WITH rebalance_cb
         should disconnect:
     Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```
Could you please evaluate the test script below? (execute with `mocha --require coffee-script/register test.coffee`)
```coffee-script
async = require "async"
Kafka = require "node-rdkafka"

getConfig = ->
  rnd = Math.floor Math.random() * 10000000

  host:    "localhost:9092"
  topic:   "test_topic_#{rnd}"
  groupId: "test_groupId_#{rnd}"

produceData = (options, amount = 100, cb) ->
  p = new Kafka.Producer "metadata.broker.list": options.host

  p.once "ready", ->
    async.eachSeries [1..amount], (i, cb) ->
      p.produce options.topic, null, Buffer.from JSON.stringify count: i
      setTimeout cb, 10
    , -> p.disconnect -> cb?()

  p.connect()

getConsumer = (options, cb) ->
  consumerOptions =
    # "debug":                "all"
    "group.id":             options.groupId
    "metadata.broker.list": options.host

  if options.rebalance
    consumerOptions["rebalance_cb"] = true

  c = Kafka.KafkaConsumer consumerOptions

  c.on "event.log", (log) -> console.log "log", log
  c.on "rebalance",       -> console.log "rebalance"

  c.once "ready", ->
    c.subscribe [ options.topic ]
    cb null, c

  c.connect()

describe "Consumer diconnect", ->
  describe "WITHOUT rebalance_cb", ->
    config   = getConfig()
    consumer = null

    before (done) ->
      @timeout 10000
      produceData config, 100, done

    before (done) ->
      @timeout 10000
      getConsumer config, (error, c) ->
        throw error if error
        consumer = c
        done()

    it "should consume data", (done) ->
      @timeout 10000
      messages = []
      callback = done
      test     = -> not messages?.length
      iteratee = (cb) ->
        consumer.consume 20, (error, msgs) ->
          return cb error if error
          messages = msgs
          cb()

      async.whilst test, iteratee, callback
      produceData config, 1000

    it "should disconnect", (done) ->
      @timeout 10000
      consumer.disconnect done

  describe "WITH rebalance_cb", ->
    config   = getConfig()
    consumer = null

    before (done) ->
      @timeout 10000
      produceData config, 100, done

    before (done) ->
      @timeout 10000
      getConsumer (Object.assign {}, config, rebalance: true), (error, c) ->
        throw error if error
        consumer = c
        done()

    it "should consume data", (done) ->
      @timeout 10000
      messages = []
      callback = done
      test     = -> not messages?.length
      iteratee = (cb) ->
        consumer.consume 20, (error, msgs) ->
          return cb error if error
          messages = msgs
          cb()

      async.whilst test, iteratee, callback
      produceData config, 1000

    it "should disconnect", (done) ->
      @timeout 10000
      consumer.disconnect done
```

**Comment by sprijk** [comment]
I am getting these debug warnings a lot when disconnecting:

```
[thrd:main]: Group "test-groupId-6634858": waiting for rebalance_cb, 1 toppar(s), 0 unassignment(s), 0 commit(s), wait-unassign flag, (state up, join-state wait-revoke-rebalance_cb) before terminating
```

Is this a `librdkafka` thing, and should I open an issue there?

**Comment by erik-stephens** [comment]
I bumped into this issue before.  I tracked it to [`self.isConnected()`](https://github.com/Blizzard/node-rdkafka/blob/5307f8fe6e577227920362a7446156e330b77ce4/lib/kafka-consumer.js#L64) which would raise an exception when not connected.

Going off memory as this was a few months ago when I was still getting familiar with the library -   wasn't clear to me where the fault was: me, node-rdkafka, or librdkafka.  On the surface, an isConnected() function raising an exception when not connected seemed like an odd interface.  Since I couldn't find other mentions and rebalancing wasn't important to me at the time, I chalked it up to user error on my part and moved on.

**Comment by sprijk** [comment]
@erik-stephens You are probably referring to #321 ? I'll reopen that issue.

**Comment by webmakersteve** [comment]
This could be related to that, and the exception is getting gobbled up. I just merged that PR. Can you try to run these tests again using master and see if they pass?

**Comment by erik-stephens** [comment]
I re-tested.  I mis-charactized it as self.isConnected() raising an exception but it does have the flavor of "I need to be connected in order to disconnect".  I'm using kafka-consumer, not the streaming version.  For my needs, I'll be using even lower level (no subscribing, managing my own offsets), so not affecting me personally.  I see this from librdkafka logs:

> 19:14:53.263Z TRACE index.js: CGRPTERM [thrd:main]: Group "even": waiting for rebalance_cb, 1 toppar(s), 0 unassignment(s), 0 commit(s), wait-unassign flag, (state up, join-state wait-revoke-rebalance_cb) before terminating (stage=even)

My interpretation is that librdkafka is waiting for me to unassign but that fails in the default rebalance callback because we're no longer connected.  Could totally be user error on my part.  All I do is set `rebalance_cb:true` because I was interested in observing that behavior.  On shutdown, I `consumer.unsubscribe(); consumer.disconnect(cb);`.

**Comment by sprijk** [comment]
This is the exact same thing as I am seeing. If you add `rebalace_cb: true` in the `e2e` tests (of this project) for the Consumer test, it will fail.

@webmakersteve Can you check this?

**Comment by webmakersteve** [comment]
Looks like it is caused because of the `isConnected` check. I adjusted it so unassign can be called while the consumer is closing and it fixed the issue. I also made sure rebalance cb is on during the end to end tests to catch this in the future.

22c713b2d9dfbb2b0ef9d42bf2b890c4ed9e4133

**Comment by oliviertassinari** [comment]
The issue might not be `rebalance_cb` specific. I'm experiencing it too when I try to close a readable stream quickly after opening it.

**Comment by oliviertassinari** [comment]
Well, my issue is probably linked to the rebalancing. I have the following log from kafka:
> INFO [GroupCoordinator 1001]: Preparing to rebalance group indexer with old generation 7 (__consumer_offsets-9) (kafka.coordinator.group.GroupCoordinator)

**Comment by sprijk** [comment]
Nice! For me https://github.com/Blizzard/node-rdkafka/commit/22c713b2d9dfbb2b0ef9d42bf2b890c4ed9e4133 works like a charm!

**Comment by webmakersteve** [comment]
This has been merged in and is fixed.
🎉

**Comment by Pchelolo** [comment]
I'm still experiencing the same issue - when `rebalance_cb` is set to true, tests won't exit after disconnect is called.

**Comment by subk** [comment]
Same issue for me as soon as I use `consumer.consume(someCallback)`

**Comment by webmakersteve** [comment]
@Pchelolo does the callback provided to disconnect execute? Can you put debug logging on? 

@subk are you calling disconnect at the end of your tests?
