### ISSUE TITLE
node-rdkafka 2.14.0 on registry.npmjs.org has wrong version inside package.json

### ISSUE THREAD

**Issue by jmyersmsft** [Blizzard/node-rdkafka#981]
In the package.json inside https://registry.npmjs.org/node-rdkafka/-/node-rdkafka-2.14.0.tgz, the version is v2.14.2-1.HEAD. This causes problems with any system that uses or validates the version in the package-json, including the upstreams feature in Azure Artifacts.

**Comment by sharmakhushboo** [comment]
@webmakersteve @iradul , could you take a look at this?

**Comment by sharmakhushboo** [comment]
@eandersson / @BlizzTom would you be able to help us here?

**Comment by ArneSchulze** [comment]
+1

**Comment by alexzel** [comment]
+1

**Comment by jancwiok** [comment]
On github the version seems to be correct: https://github.com/Blizzard/node-rdkafka/releases/tag/v2.14.2 . But the one on npm registry is incorrect. This also cause that when running `npm install --omit=dev` still all the dev dependency from node-rdkafka are installed. This does not happen for version 2.13.0.
Could anyone take a look at this?

**Comment by shiyuanhai** [comment]
+1

` ERR_PNPM_UNEXPECTED_PKG_CONTENT_IN_STORE  Package name mismatch found while reading {"integrity":"sha512-g/I6e1/07uuy3Tjeka7JKZDhbeKeDsX0P9Lj2gsZqsfqWXnwbEfLs3AaKs2/QPts62RWiXLoBhxI7W4cREZXyw==","registry":"https://registry.npmjs.org/","tarball":"https://registry.npmjs.org/node-rdkafka/-/node-rdkafka-2.14.0.tgz"} from the store. This means that the lockfile is broken. Expected package: node-rdkafka@2.14.0. Actual package in the store by the given integrity: node-rdkafka@2.14.2-1.HEAD.`

got this error using pnpm.

**Comment by monil-panchal** [comment]
The [v2.14.0](https://www.npmjs.com/package/node-rdkafka#:~:text=Version-,2.14.0,-License) in npm registry seems to be correct, whereas the [v2.14.2](https://github.com/Blizzard/node-rdkafka/releases/tag/v2.14.2) on Github is not.

![image](https://user-images.githubusercontent.com/20757399/200802096-75cde17d-f6f2-4c50-beb4-6c05f390b566.png)



![image](https://user-images.githubusercontent.com/20757399/200801881-a1bc7e5a-4448-4ba9-a3d3-785541e0e9d4.png)

**Comment by alexzel** [comment]
Well, the only available version in npm is `v2.14.0` and  there is `v2.14.2-1.HEAD` inside the tarball.

```sh
$ npm view node-rdkafka dist.tarball
https://registry.npmjs.org/node-rdkafka/-/node-rdkafka-2.14.0.tgz

$ curl -s -O -J https://registry.npmjs.org/node-rdkafka/-/node-rdkafka-2.14.0.tgz

$ tar xzf node-rdkafka-2.14.0.tgz

$ jq .version package/package.json
"v2.14.2-1.HEAD"
```

**Comment by aikoven** [comment]
As a temporary solution, I've published corrected package as `@aikoven/node-rdkafka@2.14.0`.

**Comment by JackFreelander** [comment]
This is still broken for me and using `pnpm` this causes errors during package install.  Any ETA on a fix, perhaps a clean `2.15` build?

**Comment by GaryWilber** [comment]
I made a fix for this. Can you try version 2.14.4 - https://www.npmjs.com/package/node-rdkafka/v/2.14.4

**Comment by alexzel** [comment]
Thanks for the fix! Version 2.14.5 works well.

**Comment by sharmakhushboo** [comment]
This issue has now been fixed in the new version.
